# Generated by Django 4.2.3 on 2023-07-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
