# Generated by Django 4.2.5 on 2023-10-13 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_case', '0002_alter_testcase_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='config',
            new_name='functions',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
